name: HAMC Server Bedrock
description: Host a Bedrock Minecraft server on Home Assistant
version: 1.2.0
slug: hamc-bedrock
init: false
arch:
  - amd64
  - aarch64
ports:
  19132/udp: 19132
ports_description:
  19132/udp: Minecraft Server Port
options:
  VERSION: LATEST
  SERVER_NAME: HAMC Server
  LEVEL_NAME: World
  GAMEMODE: survival
  DIFFICULTY: normal
  ALLOW_CHEATS: false
  MAX_PLAYERS: 10
  ALLOW_LIST_USERS: ""
  LEVEL_TYPE: DEFAULT
  ONLINE_MODE: true
  ENABLE_LAN_VISIBILITY: true
  VIEW_DISTANCE: 10
  TICK_DISTANCE: 4
  PLAYER_IDLE_TIMEOUT: 30
  MAX_THREADS: 2
  LEVEL_SEED: ""
  DEFAULT_PLAYER_PERMISSION_LEVEL: member
  TEXTUREPACK_REQUIRED: false
  SERVER_AUTHORITATIVE_MOVEMENT: server-auth
  SERVER_AUTHORITATIVE_BLOCK_BREAKING: false
  EMIT_SERVER_TELEMETRY: false
  PLAYER_MOVEMENT_SCORE_THRESHOLD: 20
  PLAYER_MOVEMENT_DISTANCE_THRESHOLD: 0.3
  PLAYER_MOVEMENT_DURATION_THRESHOLD_IN_MS: 500
  CORRECT_PLAYER_MOVEMENT: false
  OPS: ""
  MEMBERS: ""
  VISITORS: ""
schema:
  VERSION: str
  SERVER_NAME: str
  LEVEL_NAME: str
  GAMEMODE: list(survival|creative|adventure)
  DIFFICULTY: list(peaceful|easy|normal|hard)
  ALLOW_CHEATS: bool
  MAX_PLAYERS: int
  ALLOW_LIST_USERS: str
  LEVEL_TYPE: list(DEFAULT|FLAT|LEGACY)
  ONLINE_MODE: bool
  ENABLE_LAN_VISIBILITY: bool
  VIEW_DISTANCE: int
  TICK_DISTANCE: int
  PLAYER_IDLE_TIMEOUT: int
  MAX_THREADS: int
  LEVEL_SEED: str
  DEFAULT_PLAYER_PERMISSION_LEVEL: list(member|operator|visitor)
  TEXTUREPACK_REQUIRED: bool
  SERVER_AUTHORITATIVE_MOVEMENT: list(client-auth|server-auth|server-auth-with-rewind)
  SERVER_AUTHORITATIVE_BLOCK_BREAKING: bool
  EMIT_SERVER_TELEMETRY: bool
  PLAYER_MOVEMENT_SCORE_THRESHOLD: int
  PLAYER_MOVEMENT_DISTANCE_THRESHOLD: float
  PLAYER_MOVEMENT_DURATION_THRESHOLD_IN_MS: int
  CORRECT_PLAYER_MOVEMENT: bool
  OPS: str
  MEMBERS: str
  VISITORS: str
backup: cold
backup_exclude:
  - "bedrock_server*"
  - "behavior_packs/vanilla*"
  - "behavior_packs/chemistry*"
  - "resource_packs/vanilla*"
  - "resource_packs/chemistry*"
map:
  - addons:rw
  - addon_config:rw
environment:
  EULA: "TRUE"


